version: "2.2"

services:
  dev:
    image: parity/rust:nightly
    working_dir: /substrate-node-template
    ports:
      - "9944:9944"
    volumes:
      - ".:/substrate-node-template"
      - "cargo-cache:/root/.cargo/registry"
    command: bash -c "cargo run --release -- --dev --ws-external"

volumes:
  cargo-cache:
