version: "2.2"

services:
  dev:
    image: parity/rust:nightly
    working_dir: /substrate-node-template
    ports:
      - "9944:9944"
    volumes:
      - ".:/substrate-node-template"
      - "cargo-registry-cache:/root/.cargo/registry"
      - "cargo-git-cache:/root/.cargo/git"
    command: cargo run --release -- --dev --ws-external

volumes:
  cargo-registry-cache:
  cargo-git-cache:
